dump_directory: "/mnt/c/users/user/downloads/BizHawk-2.9.1-win-x64/Lua/GBA/ai"
test_basenames: test_names.txt
ai_scripts_directory: "../pokemonomyth/data/ai"
aicmd_syms: "../pokemonomyth/aicmd_syms.dump"
constpool_start_to_end_map_filename: "../pokemonomyth/ai_constpool_start_to_end_map.dump"
whole_rom_filename: "../pokemonomyth/pokemonomyth_ai.gba"
